name: taskhub
description: "A simple Personal & Team Task Tracker"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0-284.0.dev

dependencies:
  app_links: ^6.4.1
  envied: ^1.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  google_sign_in: ^7.2.0
  injectable: ^2.7.1+4
  json_annotation: ^4.9.0
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.4
  envied_generator: ^1.3.2
  flutter_lints: ^6.0.0
  freezed: ^3.2.4
  go_router_builder: ^4.1.3
  injectable_generator: ^2.12.0
  json_serializable: ^6.11.3

flutter:
  uses-material-design: true
